- name: "Install rustup"
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path  -y --default-toolchain nightly -v"
  register: rustup_output
  args:
    creates: ~/.cargo/env
- debug: var=rustup_output

- name: "Check last toolchain update"
  # If file does not exists it returs true otherwise it executes the find
  shell: "test ! -f ~/.cargo/last_toolchain_check || test -n \"$(find ~/.cargo -depth 1 -iname last_toolchain_check -ctime '+12h')\""
  register: last_toolchain_check
  ignore_errors: true
- debug: var=last_toolchain_check

- debug: var=last_toolchain_check
- name: Install/update toolchains
  command: "rustup toolchain add {{ item }}"
  with_items:
    - stable
    - nightly
  register: toolchains_output
  when: last_toolchain_check | success
- debug: var=toolchains_output

- name: Touch last_toolchain_check file to avoid upgrading again
  command: "touch ~/.cargo/last_toolchain_check"
  when: last_toolchain_check | success