- name: Set hub variables
  set_fact:
    hub_version: 2.2.9
    hub_full_version: "hub-linux-amd64-2.2.9"

- name: Check if hub is installed
  stat:
    path: /usr/local/bin/hub
  register: hub_stat

- name: Download hub
  unarchive:
    remote_src: true
    src: "https://github.com/github/hub/releases/download/v{{ hub_version }}/{{ hub_full_version }}.tgz"
    dest: /tmp/
  when: not hub_stat.stat.exists

- name: Install hub
  command: "bash -x /tmp/{{ hub_full_version }}/install"
  become: true
  register: hub_output
  when: not hub_stat.stat.exists
- debug: var=hub_output

- name: Clean hub files
  command: rm -rf /tmp/{{ hub_full_version }}{,.tgz}

