
- name: Update apt cache
  apt: update_cache=yes
  when: package_update
  become: true

- name: Upgrade apt packages
  apt: upgrade=dist
  when: package_upgrade
  become: true

- name: Install apt packages
  apt: name={{item}}
  with_items: "{{ apt_packages }}"
  become: true
