- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - git
    - package_manager
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - python_pyenv
    # - python_personal
    # - python_eatfirst
    - {role: hub, tags: hub}
    - zsh-autoenv
    - rg
    - exa
    - tmux
    - fzf
    - gnome_do
    - rust
    - {role: osx, when: ansible_os_family == "Darwin"}