- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - pyenv
    - hub
    - zsh-autoenv
    - rg
    - exa
    - ccat
    - tmux
    - fzf
    - {role: osx, when: ansible_os_family == "Darwin"}
