- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  roles:
    - git
    - {role: package_manager, tags: ['bootstrap']}
    - {role: zsh, tags: ['bootstrap']}
    - vim
    - {role: ~/.ansible/roles/suzuki-shunsuke.pyenv, pyenv_is_dependencies_installed: yes}
    - ~/.ansible/roles/suzuki-shunsuke.pyenv-virtualenv
    - ~/.ansible/roles/suzuki-shunsuke.pyenv-module
    - python_virtualenv
    - hub
    - zsh-autoenv
    - rg
    - exa
    - ccat
    - tmux
    - fzf
    - {role: osx, when: ansible_os_family == "Darwin"}
