
- name: Make sure zsh is installed
  apt: name=zsh state=present
  become: true

- name: Get zsh path
  command: which zsh
  register: zsh_path
  changed_when: no

- name: Change default shell to zsh
  user:
    name: "{{ ansible_user }}"
    shell: "{{ zsh_path.stdout }}"
  become: yes
