
# Installation and setup
- include: "{{ ansible_os_family | lower }}.yml"

# Configuration
- name: Check if zshrc already exists
  stat: path="{{dotfiles_user_home}}/.zshrc"
  register: zshrc_stat

- name: Back up zshrc if it exists
  command: mv ~/.zshrc ~/.zshrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.zshrc.bak"
  when: zshrc_stat.stat.exists

- include: prezto.yml
  when: zsh_prezto

- name: Copy minimal zshrc
  copy: src=zshrc_minimal dest={{dotfiles_user_home}}/.zshrc
  when: not zsh_prezto
