- name: python-binary-memcached virtualenv
  pyenv:
    subcommand: virtualenv
    version: "{{ latest_python_36 }}"
    virtualenv_name: python-binary-memcached

- name: Set pyenv local version
  command: "pyenv local {{ item }} jupyter3 tools3"
  args:
    chdir: "~/p/personal/{{ item }}"
    creates: "~/p/personal/{{ item }}/.python-version"
  with_items:
    - python-binary-memcached
