- name: "Install Python"
  pyenv:
    version: "{{ item }}"
  with_items:
    - "{{ latest_python_35 }}"
    - "{{ latest_python_36 }}"
    - "{{ latest_python_37 }}"

- name: virtualenv for Jupyter
  pyenv:
    subcommand: virtualenv
    version: "{{ latest_python_36 }}"
    virtualenv_name: jupyter3

- name: virtualenv for Python 3 tools
  pyenv:
    subcommand: virtualenv
    version: "{{ latest_python_36 }}"
    virtualenv_name: tools3

- name: Install jupyter
  pip:
    name: jupyter
    state: latest
    executable: "{{ pyenv_root }}/versions/jupyter3/bin/pip"

- name: Run ipykernel module
  command: "{{ pyenv_root }}/versions/jupyter3/bin/python -m ipykernel install --user"
  args:
    creates: "~/Library/Jupyter/kernels/python3"

- name: Install youtube-dl
  pip:
    name: youtube-dl
    state: latest
    executable: "{{ pyenv_root }}/versions/tools3/bin/pip"
