- name: "Install Python {{ latest_python_27 }}"
  pyenv:
    version: "{{ latest_python_27 }}"

- name: virtualenv for IPython
  pyenv:
    subcommand: virtualenv
    version: "{{ latest_python_27 }}"
    virtualenv_name: ipython2

- name: virtualenv for Python 2 tools
  pyenv:
    subcommand: virtualenv
    version: "{{ latest_python_27 }}"
    virtualenv_name: tools2

- name: Install ipykernel
  pip:
    name: ipykernel
    state: latest
    executable: "{{ pyenv_root }}/versions/tools2/bin/pip"

- name: Run ipykernel module
  command: "{{ pyenv_root }}/versions/tools2/bin/python -m ipykernel install --user"
  args:
    creates: "~/Library/Jupyter/kernels/python2"

- name: Install rename
  pip:
    name: rename
    state: latest
    executable: "{{ pyenv_root }}/versions/tools2/bin/pip"
